### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by ghost** [mailinneberg/BlueBorne#9]
I did everything in the directions which wasn't much and cant run the code. Can someone give a more detailed explanation of how to use this?

DON'T DOWNLOAD. THIS IS FAKE AND JUST BLUEMAHO RENAMED.

**Comment by BrandonHall6518** [comment]
Nvm just figured part of it out you have to rename coderun to maho. Which allows you to run ./blueborn.py and that opens a gui interface.

**Comment by tminus44** [comment]
I am able to get the GUI interface but when I click start scan I get: 

Traceback (most recent call last):
  File "blueborn.py", line 436, in StartInquiryScan
    self.monscreen.DeleteRows(0,self.monscreen.GetNumberRows(),True)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/grid.py", line 1277, in DeleteRows
    return _grid.Grid_DeleteRows(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at ../src/generic/grid.cpp(1392) in DeleteRows(): Called wxGridStringTable::DeleteRows(pos=0, N=0)
Pos value is invalid for present table with 0 rows

**Comment by BrandonHall6518** [comment]
Currently I don't have a Bluetooth adapter to use but I have one coming into from the mail so when it gets here I'll have a look into it and see what I can do.

**Comment by BrandonHall6518** [comment]
Also seems to be that the GUI is actually bluemaho which was stolen and edited to appear as a blueborne gui. Which also leads me to believe the rest of it is also fake or stolen content.

**Comment by BrandonHall6518** [comment]
Last comment all this is a someone trying to seem cool but most of it is a bunch of garbage bs that was stolen and renamed

**Comment by PrinceKK300188** [comment]
- ~~~~ close
